owner: canonical
repo: ubuntu-engineering-upptime

sites:
  - name: Appstream
    url: https://appstream.ubuntu.com/
  - name: Autopkgtest
    url: https://autopkgtest.ubuntu.com/
  - name: Autopkgtest Staging
    url: https://autopkgtest.staging.ubuntu.com/
  - name: Connectivity Checker
    url: http://connectivity-check.ubuntu.com
  - name: Ddebs
    url: https://ddebs.ubuntu.com/
#  - name: DebugInfoD
#    url: TBD
  - name: Errors
    url: https://errors.ubuntu.com/
  - name: GeoIP
    url: https://geoip.ubuntu.com/
  - name: Geonames
    url: https://geoname-lookup.ubuntu.com/
  - name: Lp retracers
    url: https://launchpad-retracer.ubuntu.com/
  - name: Manpages
    url: https://manpages.ubuntu.com/
  - name: Manpages Staging
    url: https://manpages.staging.ubuntu.com/
  - name: Merge-o-matic
    url: https://merges.ubuntu.com/
  - name: Packages
    url: http://packages.ubuntu.com/
  - name: Sponsoring Report
    url: http://sponsoring-reports.ubuntu.com/
  - name: SRU Report
    url: https://ubuntu-archive-team.ubuntu.com/pending-sru.html
  - name: Transitions Tracker
    url: https://transitions.ubuntu.com/
  - name: Ubuntu Metrics
    url: https://ubuntu-release.kpi.ubuntu.com
  - name: Update Excuses
    url: https://ubuntu-archive-team.ubuntu.com/proposed-migration/update_excuses.html
  - name: Upki Mirror
    url: https://crlite.ubuntu.com/k8s-prod-upki-mirror-ps7-default-upki-mirror-k8s/
  - name: Versions
    url: https://people.canonical.com/~platform/desktop/versions/ubuntu-desktop.html

status-website:
  baseUrl: /ubuntu-engineering-upptime
  logoUrl: https://assets.ubuntu.com/v1/a7e3c509-Canonical%20Ubuntu.svg
  name: Ubuntu services monitoring
  favicon: https://assets.ubuntu.com/v1/49a1a858-favicon-32x32.png
  introTitle: "Status of the services maintained by Ubuntu Engineering."
  navbar:
    - title: Status
      href: /ubuntu-engineering-upptime
    - title: GitHub
      href: https://github.com/canonical/ubuntu-engineering-upptime
